export const CareerInfo = [
  {
    company: "Bittreo",
    term: "May 2nd, 2022 - present",
    link: "https://bittreo.com",
    description: [
      "-Develop Dashboard application for Sellers and Tellers ofcryptocurrencies.",
      "-Node.js, Express.js configuration and custom extensions for MVC server-side logic",
      "-Vue.js, Vuex implementation for front-end",
    ],
    technologies: [
      "JavaScript",
      "Vue.js",
      "Vuex",
      "AWS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "etc",
    ],
  },
  {
    company: "App Growth Network -Fullstack Developer(Contract)",
    term: "January 5th, 2022 - April 30th, 2022",
    link: "https://appgrowthnetwork.com",
    description: [
      "-Develop Dashboard application for marketers of mobile application",
      "-AWS Amplify configuration and custom extensions for MVC server-side logic",
      "-React, Redux implementation for front-end",
    ],
    technologies: [
      "JavaScript",
      "React",
      "Redux",
      "AWS",
      "AWS Amplify",
      "Python",
      "Node.js",
      "Amazon DynamoDB",
      "GraphQL",
      "etc",
    ],
  },
  {
    company: "Casareal Inc. -Fullstack Developer(Fulltime)",
    term: "March 1th, 2018 - February 28th, 2021",
    link: "https://www.casareal.co.jp",
    description: [
      "-Laravel framework configuration and custom extensions for MVC server-side logic",
      "-Spring framework configuration and custom extensions for MVC server-side logic",
      "-MySQL configuration as attached data-store for above",
      "-HTML5, CSS, jQuery implementation for front-end",
      "-Developed and structured 3 web application with PHP, Laravel, MySQL and AWS for clients",
      "-Developed and structured 1 web application with Java, Spring Boot, MySQL and AWS for the client",
    ],
    technologies: [
      "PHP",
      "Java",
      "JavaScript",
      "Laravel",
      "Spring",
      "JQuery",
      "HTML5",
      "etc",
    ],
  },
  {
    company: "Soft Hyperion Inc. -Fullstack Developer(Fulltime)",
    term: "Feburuary 1th, 2016 - January 31th, 2021",
    link: "https://soft-hyperion.com",
    description: [
      "-Develop Dashboard application for Sellers and Tellers ofcryptocurrencies.",
      "-Node.js, Express.js configuration and custom extensions for MVC server-side logic",
      "-Vue.js, Vuex implementation for front-end",
    ],
    technologies: [
      "Java",
      "JavaScript",
      "Spring",
      "JQuery",
      "HTML5",
      "CSS3",
      "MySQL",
      "etc",
    ],
  },
];
